### ISSUE TITLE
Update to 1.2.30 causes "Internal Server Error" when updating an organization

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad.Client#28]
When trying to update an organization `UpdateOrganizationAsync` I get the following error:

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> Zammad.Client.Core.ZammadException: Internal Server Error
   bei Zammad.Client.Core.ZammadClient.<SendAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Zammad.Client.Core.ZammadClient.<PutAsync>d__9`1.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bei [My application].createOrUpdateOrganization() in [My class]:Zeile 129.
---> (Interne Ausnahme #0) Zammad.Client.Core.ZammadException: Internal Server Error
   bei Zammad.Client.Core.ZammadClient.<SendAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Zammad.Client.Core.ZammadClient.<PutAsync>d__9`1.MoveNext()<---

**Comment by Asesjix** [comment]
That is a server error from zammad.
Which exceptions contains the aggregate exception?
ps: why do you run the calls in sync?
```
    try
    {
        client.UpdateOrganizationAsync(…);
    }
    catch (AggregateException ae)
    {
        // ae.InnerExceptions
    }
```

**Comment by MarvinKlar** [comment]
I already found the solution it the logs. Seems to be my bad.

Cause the calling method is sync.
