### ISSUE TITLE
Creator and customer of ticket does not get updated

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad.Client#29]
When creating a ticket, I set the `CustomerId` and `CreatedById` (and also the `OrganizationId`) like this:
![screenshot_1](https://user-images.githubusercontent.com/34421947/46526960-19e3b780-c890-11e8-83a2-630c2c553860.png)

The JSON of the ticket does look like this (Serialized with `JSONConvert.SerializeObject()`):
`{"id":0,"group_id":1,"priority_id":2,"state_id":1,"organization_id":30,"number":null,"title":"The title","owner_id":0,"customer_id":234,"note":"Importiertes Ticket aus E-Mail","first_response_at":null,"first_response_escalation_at":null,"first_response_in_min":null,"first_response_diff_in_min":null,"close_at":null,"close_escalation_at":null,"close_in_min":null,"close_diff_in_min":null,"update_escalation_at":null,"update_in_min":null,"update_diff_in_min":null,"last_contact_at":null,"last_contact_agent_at":null,"last_contact_customer_at":null,"last_owner_update_at":null,"create_article_type_id":null,"create_article_sender_id":null,"article_count":0,"escalation_at":null,"pending_time":null,"type":null,"time_unit":null,"preferences":null,"updated_by_id":null,"created_by_id":234,"created_at":"0001-01-01T00:00:00+00:00","updated_at":"0001-01-01T00:00:00+00:00"}
`

As you can see, `"created_by_id":234`, `"customer_id":234` and also `"organization_id":30` is set. 

But, the customer/creator is not set in the ticket in Zammad: (Actually the creator of the ticket is the user, who imports the ticket to Zammad.)
![screenshot_2](https://user-images.githubusercontent.com/34421947/46527146-9e363a80-c890-11e8-8d77-5b4e3c94a797.png)

Am I doing something wrong?

**Comment by Asesjix** [comment]
You must use the "OnBehalfOf" Feature.
https://docs.zammad.org/en/latest/api-intro.html#example-curl-request-on-behalf-of-a-different-user

https://github.com/Asesjix/Zammad.Client/blob/3c1884020e85b96ab0b38ca25785b714cb639b90/src/Zammad.Client/ZammadAccount.cs#L102-L111

**Comment by MarvinKlar** [comment]
Thank you very very much!
