### ISSUE TITLE
Unable to set custom attributes

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad.Client#38]
I created a custom attribute for a user in Zammad. Now, I want to edit this attribute with the API. But there is no way to do this. The `Zammad.Client.Resources.User` object, doesn't allow custom attributes.

**Comment by saschaarlt** [comment]
add a Pull request to solve this issue / enhancement.

**Comment by alainseys** [comment]
@MarvinKlar  is this still an active issue i see this is handled in PR #42 please check if this can be closed or not .
